Added the event page for gsoc seminar
kossiitkgp/kossiitkgp.github.io pull request #62
Opened 2017-05-07 20:47 UTC by tibrewalpratik17

Please critically review it. Though i did nothing much other than content writing still need your reviews.

2017-05-08 04:10 UTC, americast submitted a review, later dismissed
Looks good! Thanx @tibrewalpratik17 !

2017-05-08 12:59 UTC, tibrewalpratik17 commented
@americast review the github workshop page too

2017-05-09 13:18 UTC, tibrewalpratik17 commented
ping @americast

2017-05-10 09:49 UTC, pranitbauva1997 requested changes
Good! But I think you haven't added it to the events/index.html which you ideally should in order to be accessible from the website.

2017-05-10 09:52 UTC, pranitbauva1997 requested changes
Good! Some changes need to be incorporated before merging.

2017-05-10 09:52 UTC, pranitbauva1997 commented on events/github.html
> +          <img src="assets/images/wireframe/white-image.png" class="ui large bordered rounded image">
This isn't being rendered.

2017-05-10 09:52 UTC, pranitbauva1997 commented on events/github.html
> +      <h1 class="ui inverted header" style="font-size: 4rem">
Too much of unnecessary spaces over here. Let's move the actual content a little above if it is feasible.

2017-05-10 09:52 UTC, pranitbauva1997 commented on events/gsocseminar.html
> +          <img src="assets/images/wireframe/white-image.png" class="ui large bordered rounded image">
Again not rendered. Plus again the same too much gap issue as above.

2017-05-12 15:23 UTC, americast approved these changes
Looks cool to me! Thanx @tibrewalpratik17 !

2017-05-12 15:58 UTC, pranitbauva1997 approved these changes
The existing problems with this PR (which can be merged, but issue needs to be created) are:
 * The GSoC seminar should not be in "Past Events"
 * Github workshop isn't present in the main events page.
 * The image isn't being rendered

2017-05-12 16:29 UTC, merged